### ISSUE TITLE
'remove lapack linking' merge forces scipy dependency up to 0.13

### ISSUE THREAD

**Issue by matthew-brett** [nipy/nipy#344]
See `nipy.labs` errors in https://travis-ci.org/matthew-brett/nipy/jobs/77317008

We previously depended on scipy >= 0.7.0, but I think that the remove lapack merge means that we now need scipy 0.13.0 which is much more recent.  This is in order to use `scipy.linalg._fblas` (arrived in scipy 0.12) and then `scipy.linalg._fblas.dsymm` (arrived in scipy 0.13).

The question is, what to do now.  Options I can see:

* revert the 'remove lapack linking' merge on the basis that the convenience of not linking to external lapack is less then the convenience of being able to use scipy < 0.13;
* put some import checks around the nipy.labs and nipy.labs testing code that skips the relevant tests when the scipy version is too low.

Alexis - what do you think?

**Comment by alexis-roche** [comment]
I think that we should minimize efforts here given our limited manpower and the fact that the nipy package itself is getting deprecated... So I think it's fine to revert to the old, historical "lapack needed" situation.

**Comment by matthew-brett** [comment]
OK - what I propose to do for now, is to revert the 'remove lapack' merge, and reopen the contents as a PR. 

Any comments before I go ahead with that?

**Comment by satra** [comment]
@alexis-roche, @matthew-brett - since this merge was intended to simplify install of nipy in the context of  mkl, it affects users who use conda + mkl as their platform. i'm assuming that reverting this merge will affect such an environment. 

if so, is the plan to tell users to shift over to nireg and update their scripts?

**Comment by matthew-brett** [comment]
Satra - I think our priority now is to get down to no test errors.   So I propose to revert this merge and re-open the original PR with the intention of merging again soon, when we can do that without test errors.  Sound reasonable to you - Satra, Alexis?

**Comment by satra** [comment]
@matthew-brett - from a test perspective that sounds fine. and the pr solution would be to allow for skipping tests on (scipy < 0.13)?

**Comment by matthew-brett** [comment]
Skipping the tests for scipy < 0.13 is one option, if we can't find a better one.

Is the mkl a big issue for you?   I guess we'll do a nipy release in the next few weeks.

Alexis - is there another way of working round the mkl issue that you can think of?

**Comment by satra** [comment]
on our cluster, conda/anaconda is the preferred python solution (not that everybody gets accelerate), and i suspect that's true of many users these days. for folks that have mkl, i generally recommend folks to install my (not so often synced) version of mkl hacking nipy PR. so it was really nice to have a clean solution. would it be possible to tag the current master, so that i can point people to that? i can always point them to a specific hashtag.

so it's not a big issue, but was a nice convenience to have.

**Comment by alexis-roche** [comment]
Given that my patch currently only works with scipy >= 0.13 and python < 3,
I would rather suggest to point conda+mkl users to nireg if they want to
make sure that they avoid problems (at least using the registration stuff).
I can make the patch work for python 3, but I don't see any solution to
deal with scipy < 0.13 (other than linking with lapack on build).

Using nireg is by far the most robust technical solution because nireg does
not use blas/lapack in any way. I don't know how inconvenient it would be
for people to switch right now, but I feel that it's on everyone's best
interest that the switch happens as soon as possible.

On Thu, Aug 27, 2015 at 5:39 PM, Satrajit Ghosh <notifications@github.com>
wrote:

> on our cluster, conda/anaconda is the preferred python solution (not that
> everybody gets accelerate), and i suspect that's true of many users these
> days. for folks that have mkl, i generally recommend folks to install my
> (not so often synced) version of mkl hacking nipy PR. so it was really nice
> to have a clean solution. would it be possible to tag the current master,
> so that i can point people to that? i can always point them to a specific
> hashtag.
>
> so it's not a big issue, but was a nice convenience to have.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nipy/nipy/issues/344#issuecomment-135472207>.
>



-- 
Lead Clinical Research
Advanced Clinical Imaging Technology
Siemens/CHUV/EPFL
1015 Lausanne, Switzerland
Phone: +41 21 545 9972
https://sites.google.com/site/alexisroche

**Comment by matthew-brett** [comment]
Closed by commit revert commit c9520f4, I believe. 

This reverted the lapack linking merge.

 Please re-open if I'm wrong.
