### ISSUE TITLE
realign test code style

### ISSUE THREAD

**Issue by TheChymera** [nipy/nipy#411]
@matthew-brett you [pointed out that some capitalization might be needed](https://github.com/nipy/nipy/pull/410#r78789690). What exactly should be capitalized - and per what recommendation? [This](https://www.python.org/dev/peps/pep-0008/#global-variable-names) is the only style guide I found for capitalization, and I believe it makes no recommendations pertaining to our image object instances.

**Comment by matthew-brett** [comment]
I was suggesting using all-caps for the global variable names. No, it's not in the PEP, just a convention that is fairly common, and that I find helpful:

http://stackoverflow.com/questions/2601269/arguments-local-variables-and-global-variables-coding-convention-in-python

**Comment by TheChymera** [comment]
From the answers in that thread you linked to - does it not seem more common that using different naming schemes for local and global variables is bad practice?

I for one had no trouble finding where the image object/lists were defined.

**Comment by matthew-brett** [comment]
From that thread I see this "Why is there a need to distinguish between arguments and local variables" - but that's not relevant to us.  Then further down there's this:

"It is usually obvious in python which variables are local and which are global, since to modify a global variable you have to declare it using the the global keyword at the start of a function. However I sometimes add a global declaration even if it is not necessary for python to compile it, in order to emphasize that an object is global - e.g. modifying a mutable global data-structure.

Arguments should be obvious because they are in the function declaration.

As others have said constants should be in UPPER_CASE_WITH_UNDERSCORES, which is a convention shared by many languages."

So maybe I should have said it differently - I like module level global constants to be in uppercase, as this person does.  Module level global variables, used as variables rather than constants, will be easy to see, because they need `global` declarations inside the function using them.

**Comment by TheChymera** [comment]
Ah, so im and ims [here](https://github.com/nipy/nipy/blob/master/nipy/algorithms/registration/tests/test_fmri_realign4d.py#L26) are constants, and they and only they should be capitalized - y?

**Comment by matthew-brett** [comment]
Right.
