### ISSUE TITLE
Move to pytest?

### ISSUE THREAD

**Issue by yarikoptic** [nipy/nipy#499]
Seems still on `nose`, which is dissolving in the past. If there is a future for `nipy`, even if to maintain, most likely should migrate to `pytest`.  In DataLad we did 'minimal migration' by providing all kinds of adapters https://github.com/datalad/datalad/blob/maint/datalad/tests/utils_pytest.py#L71 to make migration 'minimalistic' and smoother.

WDYT?

**Comment by musicinmybrain** [comment]
For context, Fedora Linux [deprecated the `python-nose` package](https://fedoraproject.org/wiki/Changes/DeprecateNose) in Fedora 32, which was released about three years ago.

The migration to [nose3](https://github.com/jayvdb/nose3) in https://github.com/nipy/nipy/commit/526f697637e9de19a470ee3a16e0a756987d580f helps a little, I guess.

**Comment by musicinmybrain** [comment]
> thank you @musicinmybrain and @matthew-brett who did that move to `nose3` fork -- unfortunately doesn't help in debian land since there is no package of that fork.

I only pointed to it; I had nothing to do with it. As someone who helps maintain the `python-nipy` package in Fedora Linux, we’re in the same situation. It doesn’t really help me unless we add a `python-nose3` package, and since `nose3` provides `import nose`, that would require some wider discussion. It’s not immediately obvious whether or not it would be wanted.

**Comment by musicinmybrain** [comment]
Works for meWorks for me with e5e063b09d094ff79d2089261828fd2b2c843ab6; see https://github.com/nipy/nipy/issues/526#issuecomment-1759978210.
